#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoiBong.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLBD")]
	public partial class MyDatabaseQLDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertACCOUNT(ACCOUNT instance);
    partial void UpdateACCOUNT(ACCOUNT instance);
    partial void DeleteACCOUNT(ACCOUNT instance);
    partial void InsertBANTHANG(BANTHANG instance);
    partial void UpdateBANTHANG(BANTHANG instance);
    partial void DeleteBANTHANG(BANTHANG instance);
    partial void InsertCAUTHU(CAUTHU instance);
    partial void UpdateCAUTHU(CAUTHU instance);
    partial void DeleteCAUTHU(CAUTHU instance);
    partial void InsertDOIBONG(DOIBONG instance);
    partial void UpdateDOIBONG(DOIBONG instance);
    partial void DeleteDOIBONG(DOIBONG instance);
    partial void InsertTRONGTAI(TRONGTAI instance);
    partial void UpdateTRONGTAI(TRONGTAI instance);
    partial void DeleteTRONGTAI(TRONGTAI instance);
    partial void InsertQUYDINH(QUYDINH instance);
    partial void UpdateQUYDINH(QUYDINH instance);
    partial void DeleteQUYDINH(QUYDINH instance);
    partial void InsertHUANLUYENVIEN(HUANLUYENVIEN instance);
    partial void UpdateHUANLUYENVIEN(HUANLUYENVIEN instance);
    partial void DeleteHUANLUYENVIEN(HUANLUYENVIEN instance);
    partial void InsertTRANDAU_TRONGTAI(TRANDAU_TRONGTAI instance);
    partial void UpdateTRANDAU_TRONGTAI(TRANDAU_TRONGTAI instance);
    partial void DeleteTRANDAU_TRONGTAI(TRANDAU_TRONGTAI instance);
    partial void InsertTRANDAU(TRANDAU instance);
    partial void UpdateTRANDAU(TRANDAU instance);
    partial void DeleteTRANDAU(TRANDAU instance);
    partial void InsertLOAIBANTHANG(LOAIBANTHANG instance);
    partial void UpdateLOAIBANTHANG(LOAIBANTHANG instance);
    partial void DeleteLOAIBANTHANG(LOAIBANTHANG instance);
    #endregion
		
		public MyDatabaseQLDBDataContext() : 
				base(global::QuanLyDoiBong.Properties.Settings.Default.QLBDConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public MyDatabaseQLDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDatabaseQLDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDatabaseQLDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDatabaseQLDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ACCOUNT> ACCOUNTs
		{
			get
			{
				return this.GetTable<ACCOUNT>();
			}
		}
		
		public System.Data.Linq.Table<BANTHANG> BANTHANGs
		{
			get
			{
				return this.GetTable<BANTHANG>();
			}
		}
		
		public System.Data.Linq.Table<CAUTHU> CAUTHUs
		{
			get
			{
				return this.GetTable<CAUTHU>();
			}
		}
		
		public System.Data.Linq.Table<DOIBONG> DOIBONGs
		{
			get
			{
				return this.GetTable<DOIBONG>();
			}
		}
		
		public System.Data.Linq.Table<TRONGTAI> TRONGTAIs
		{
			get
			{
				return this.GetTable<TRONGTAI>();
			}
		}
		
		public System.Data.Linq.Table<QUYDINH> QUYDINHs
		{
			get
			{
				return this.GetTable<QUYDINH>();
			}
		}
		
		public System.Data.Linq.Table<HUANLUYENVIEN> HUANLUYENVIENs
		{
			get
			{
				return this.GetTable<HUANLUYENVIEN>();
			}
		}
		
		public System.Data.Linq.Table<TRANDAU_TRONGTAI> TRANDAU_TRONGTAIs
		{
			get
			{
				return this.GetTable<TRANDAU_TRONGTAI>();
			}
		}
		
		public System.Data.Linq.Table<TRANDAU> TRANDAUs
		{
			get
			{
				return this.GetTable<TRANDAU>();
			}
		}
		
		public System.Data.Linq.Table<LOAIBANTHANG> LOAIBANTHANGs
		{
			get
			{
				return this.GetTable<LOAIBANTHANG>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ACCOUNT")]
	public partial class ACCOUNT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _USERNAME;
		
		private string _PASS;
		
		private System.Nullable<byte> _TYPEACC;
		
		private System.Nullable<System.DateTime> _NGAYLAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnPASSChanging(string value);
    partial void OnPASSChanged();
    partial void OnTYPEACCChanging(System.Nullable<byte> value);
    partial void OnTYPEACCChanged();
    partial void OnNGAYLAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAPChanged();
    #endregion
		
		public ACCOUNT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASS", DbType="NChar(50)")]
		public string PASS
		{
			get
			{
				return this._PASS;
			}
			set
			{
				if ((this._PASS != value))
				{
					this.OnPASSChanging(value);
					this.SendPropertyChanging();
					this._PASS = value;
					this.SendPropertyChanged("PASS");
					this.OnPASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPEACC", DbType="TinyInt")]
		public System.Nullable<byte> TYPEACC
		{
			get
			{
				return this._TYPEACC;
			}
			set
			{
				if ((this._TYPEACC != value))
				{
					this.OnTYPEACCChanging(value);
					this.SendPropertyChanging();
					this._TYPEACC = value;
					this.SendPropertyChanged("TYPEACC");
					this.OnTYPEACCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYLAP
		{
			get
			{
				return this._NGAYLAP;
			}
			set
			{
				if ((this._NGAYLAP != value))
				{
					this.OnNGAYLAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP = value;
					this.SendPropertyChanged("NGAYLAP");
					this.OnNGAYLAPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BANTHANG")]
	public partial class BANTHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACT;
		
		private string _MADB;
		
		private string _MATD;
		
		private byte _PHUTGHIBAN;
		
		private System.Nullable<char> _LOAIBT;
		
		private EntityRef<CAUTHU> _CAUTHU;
		
		private EntityRef<DOIBONG> _DOIBONG;
		
		private EntityRef<TRANDAU> _TRANDAU;
		
		private EntityRef<LOAIBANTHANG> _LOAIBANTHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACTChanging(string value);
    partial void OnMACTChanged();
    partial void OnMADBChanging(string value);
    partial void OnMADBChanged();
    partial void OnMATDChanging(string value);
    partial void OnMATDChanged();
    partial void OnPHUTGHIBANChanging(byte value);
    partial void OnPHUTGHIBANChanged();
    partial void OnLOAIBTChanging(System.Nullable<char> value);
    partial void OnLOAIBTChanged();
    #endregion
		
		public BANTHANG()
		{
			this._CAUTHU = default(EntityRef<CAUTHU>);
			this._DOIBONG = default(EntityRef<DOIBONG>);
			this._TRANDAU = default(EntityRef<TRANDAU>);
			this._LOAIBANTHANG = default(EntityRef<LOAIBANTHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACT", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACT
		{
			get
			{
				return this._MACT;
			}
			set
			{
				if ((this._MACT != value))
				{
					if (this._CAUTHU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACTChanging(value);
					this.SendPropertyChanging();
					this._MACT = value;
					this.SendPropertyChanged("MACT");
					this.OnMACTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADB", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADB
		{
			get
			{
				return this._MADB;
			}
			set
			{
				if ((this._MADB != value))
				{
					if ((this._CAUTHU.HasLoadedOrAssignedValue || this._DOIBONG.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADBChanging(value);
					this.SendPropertyChanging();
					this._MADB = value;
					this.SendPropertyChanged("MADB");
					this.OnMADBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATD", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATD
		{
			get
			{
				return this._MATD;
			}
			set
			{
				if ((this._MATD != value))
				{
					if (this._TRANDAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATDChanging(value);
					this.SendPropertyChanging();
					this._MATD = value;
					this.SendPropertyChanged("MATD");
					this.OnMATDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHUTGHIBAN", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte PHUTGHIBAN
		{
			get
			{
				return this._PHUTGHIBAN;
			}
			set
			{
				if ((this._PHUTGHIBAN != value))
				{
					this.OnPHUTGHIBANChanging(value);
					this.SendPropertyChanging();
					this._PHUTGHIBAN = value;
					this.SendPropertyChanged("PHUTGHIBAN");
					this.OnPHUTGHIBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAIBT", DbType="NChar(1)")]
		public System.Nullable<char> LOAIBT
		{
			get
			{
				return this._LOAIBT;
			}
			set
			{
				if ((this._LOAIBT != value))
				{
					if (this._LOAIBANTHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLOAIBTChanging(value);
					this.SendPropertyChanging();
					this._LOAIBT = value;
					this.SendPropertyChanged("LOAIBT");
					this.OnLOAIBTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAUTHU_BANTHANG", Storage="_CAUTHU", ThisKey="MACT,MADB", OtherKey="MACT,MADB", IsForeignKey=true)]
		public CAUTHU CAUTHU
		{
			get
			{
				return this._CAUTHU.Entity;
			}
			set
			{
				CAUTHU previousValue = this._CAUTHU.Entity;
				if (((previousValue != value) 
							|| (this._CAUTHU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CAUTHU.Entity = null;
						previousValue.BANTHANGs.Remove(this);
					}
					this._CAUTHU.Entity = value;
					if ((value != null))
					{
						value.BANTHANGs.Add(this);
						this._MACT = value.MACT;
						this._MADB = value.MADB;
					}
					else
					{
						this._MACT = default(string);
						this._MADB = default(string);
					}
					this.SendPropertyChanged("CAUTHU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOIBONG_BANTHANG", Storage="_DOIBONG", ThisKey="MADB", OtherKey="MADB", IsForeignKey=true)]
		public DOIBONG DOIBONG
		{
			get
			{
				return this._DOIBONG.Entity;
			}
			set
			{
				DOIBONG previousValue = this._DOIBONG.Entity;
				if (((previousValue != value) 
							|| (this._DOIBONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOIBONG.Entity = null;
						previousValue.BANTHANGs.Remove(this);
					}
					this._DOIBONG.Entity = value;
					if ((value != null))
					{
						value.BANTHANGs.Add(this);
						this._MADB = value.MADB;
					}
					else
					{
						this._MADB = default(string);
					}
					this.SendPropertyChanged("DOIBONG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRANDAU_BANTHANG", Storage="_TRANDAU", ThisKey="MATD", OtherKey="MATD", IsForeignKey=true)]
		public TRANDAU TRANDAU
		{
			get
			{
				return this._TRANDAU.Entity;
			}
			set
			{
				TRANDAU previousValue = this._TRANDAU.Entity;
				if (((previousValue != value) 
							|| (this._TRANDAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRANDAU.Entity = null;
						previousValue.BANTHANGs.Remove(this);
					}
					this._TRANDAU.Entity = value;
					if ((value != null))
					{
						value.BANTHANGs.Add(this);
						this._MATD = value.MATD;
					}
					else
					{
						this._MATD = default(string);
					}
					this.SendPropertyChanged("TRANDAU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIBANTHANG_BANTHANG", Storage="_LOAIBANTHANG", ThisKey="LOAIBT", OtherKey="MABT", IsForeignKey=true)]
		public LOAIBANTHANG LOAIBANTHANG
		{
			get
			{
				return this._LOAIBANTHANG.Entity;
			}
			set
			{
				LOAIBANTHANG previousValue = this._LOAIBANTHANG.Entity;
				if (((previousValue != value) 
							|| (this._LOAIBANTHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIBANTHANG.Entity = null;
						previousValue.BANTHANGs.Remove(this);
					}
					this._LOAIBANTHANG.Entity = value;
					if ((value != null))
					{
						value.BANTHANGs.Add(this);
						this._LOAIBT = value.MABT;
					}
					else
					{
						this._LOAIBT = default(Nullable<char>);
					}
					this.SendPropertyChanged("LOAIBANTHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CAUTHU")]
	public partial class CAUTHU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACT;
		
		private string _MADB;
		
		private string _HOTEN;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _DIACHI;
		
		private string _QUOCTICH;
		
		private System.Nullable<byte> _SONAMKINHNGHIEM;
		
		private string _AVATAR;
		
		private System.Nullable<short> _SOBANTHANG;
		
		private string _VITRI;
		
		private EntitySet<BANTHANG> _BANTHANGs;
		
		private EntityRef<DOIBONG> _DOIBONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACTChanging(string value);
    partial void OnMACTChanged();
    partial void OnMADBChanging(string value);
    partial void OnMADBChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnQUOCTICHChanging(string value);
    partial void OnQUOCTICHChanged();
    partial void OnSONAMKINHNGHIEMChanging(System.Nullable<byte> value);
    partial void OnSONAMKINHNGHIEMChanged();
    partial void OnAVATARChanging(string value);
    partial void OnAVATARChanged();
    partial void OnSOBANTHANGChanging(System.Nullable<short> value);
    partial void OnSOBANTHANGChanged();
    partial void OnVITRIChanging(string value);
    partial void OnVITRIChanged();
    #endregion
		
		public CAUTHU()
		{
			this._BANTHANGs = new EntitySet<BANTHANG>(new Action<BANTHANG>(this.attach_BANTHANGs), new Action<BANTHANG>(this.detach_BANTHANGs));
			this._DOIBONG = default(EntityRef<DOIBONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACT", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACT
		{
			get
			{
				return this._MACT;
			}
			set
			{
				if ((this._MACT != value))
				{
					this.OnMACTChanging(value);
					this.SendPropertyChanging();
					this._MACT = value;
					this.SendPropertyChanged("MACT");
					this.OnMACTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADB", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADB
		{
			get
			{
				return this._MADB;
			}
			set
			{
				if ((this._MADB != value))
				{
					if (this._DOIBONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADBChanging(value);
					this.SendPropertyChanging();
					this._MADB = value;
					this.SendPropertyChanged("MADB");
					this.OnMADBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(30)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUOCTICH", DbType="NVarChar(20)")]
		public string QUOCTICH
		{
			get
			{
				return this._QUOCTICH;
			}
			set
			{
				if ((this._QUOCTICH != value))
				{
					this.OnQUOCTICHChanging(value);
					this.SendPropertyChanging();
					this._QUOCTICH = value;
					this.SendPropertyChanged("QUOCTICH");
					this.OnQUOCTICHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONAMKINHNGHIEM", DbType="TinyInt")]
		public System.Nullable<byte> SONAMKINHNGHIEM
		{
			get
			{
				return this._SONAMKINHNGHIEM;
			}
			set
			{
				if ((this._SONAMKINHNGHIEM != value))
				{
					this.OnSONAMKINHNGHIEMChanging(value);
					this.SendPropertyChanging();
					this._SONAMKINHNGHIEM = value;
					this.SendPropertyChanged("SONAMKINHNGHIEM");
					this.OnSONAMKINHNGHIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVATAR", DbType="NVarChar(500)")]
		public string AVATAR
		{
			get
			{
				return this._AVATAR;
			}
			set
			{
				if ((this._AVATAR != value))
				{
					this.OnAVATARChanging(value);
					this.SendPropertyChanging();
					this._AVATAR = value;
					this.SendPropertyChanged("AVATAR");
					this.OnAVATARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOBANTHANG", DbType="SmallInt")]
		public System.Nullable<short> SOBANTHANG
		{
			get
			{
				return this._SOBANTHANG;
			}
			set
			{
				if ((this._SOBANTHANG != value))
				{
					this.OnSOBANTHANGChanging(value);
					this.SendPropertyChanging();
					this._SOBANTHANG = value;
					this.SendPropertyChanged("SOBANTHANG");
					this.OnSOBANTHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VITRI", DbType="NVarChar(20)")]
		public string VITRI
		{
			get
			{
				return this._VITRI;
			}
			set
			{
				if ((this._VITRI != value))
				{
					this.OnVITRIChanging(value);
					this.SendPropertyChanging();
					this._VITRI = value;
					this.SendPropertyChanged("VITRI");
					this.OnVITRIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAUTHU_BANTHANG", Storage="_BANTHANGs", ThisKey="MACT,MADB", OtherKey="MACT,MADB")]
		public EntitySet<BANTHANG> BANTHANGs
		{
			get
			{
				return this._BANTHANGs;
			}
			set
			{
				this._BANTHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOIBONG_CAUTHU", Storage="_DOIBONG", ThisKey="MADB", OtherKey="MADB", IsForeignKey=true)]
		public DOIBONG DOIBONG
		{
			get
			{
				return this._DOIBONG.Entity;
			}
			set
			{
				DOIBONG previousValue = this._DOIBONG.Entity;
				if (((previousValue != value) 
							|| (this._DOIBONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOIBONG.Entity = null;
						previousValue.CAUTHUs.Remove(this);
					}
					this._DOIBONG.Entity = value;
					if ((value != null))
					{
						value.CAUTHUs.Add(this);
						this._MADB = value.MADB;
					}
					else
					{
						this._MADB = default(string);
					}
					this.SendPropertyChanged("DOIBONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BANTHANGs(BANTHANG entity)
		{
			this.SendPropertyChanging();
			entity.CAUTHU = this;
		}
		
		private void detach_BANTHANGs(BANTHANG entity)
		{
			this.SendPropertyChanging();
			entity.CAUTHU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOIBONG")]
	public partial class DOIBONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MADB;
		
		private string _TENDOIBONG;
		
		private System.Nullable<byte> _SOLUONGCAUTHU;
		
		private string _TENSANNHA;
		
		private string _TINHTHANH;
		
		private System.Nullable<System.DateTime> _NGAYTHANHLAP;
		
		private System.Nullable<short> _SOBANTHANG;
		
		private System.Nullable<short> _SOBANTHUA;
		
		private System.Nullable<short> _TONGDIEM;
		
		private EntitySet<BANTHANG> _BANTHANGs;
		
		private EntitySet<CAUTHU> _CAUTHUs;
		
		private EntitySet<HUANLUYENVIEN> _HUANLUYENVIENs;
		
		private EntitySet<TRANDAU> _TRANDAUs;
		
		private EntitySet<TRANDAU> _TRANDAUs1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADBChanging(string value);
    partial void OnMADBChanged();
    partial void OnTENDOIBONGChanging(string value);
    partial void OnTENDOIBONGChanged();
    partial void OnSOLUONGCAUTHUChanging(System.Nullable<byte> value);
    partial void OnSOLUONGCAUTHUChanged();
    partial void OnTENSANNHAChanging(string value);
    partial void OnTENSANNHAChanged();
    partial void OnTINHTHANHChanging(string value);
    partial void OnTINHTHANHChanged();
    partial void OnNGAYTHANHLAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYTHANHLAPChanged();
    partial void OnSOBANTHANGChanging(System.Nullable<short> value);
    partial void OnSOBANTHANGChanged();
    partial void OnSOBANTHUAChanging(System.Nullable<short> value);
    partial void OnSOBANTHUAChanged();
    partial void OnTONGDIEMChanging(System.Nullable<short> value);
    partial void OnTONGDIEMChanged();
    #endregion
		
		public DOIBONG()
		{
			this._BANTHANGs = new EntitySet<BANTHANG>(new Action<BANTHANG>(this.attach_BANTHANGs), new Action<BANTHANG>(this.detach_BANTHANGs));
			this._CAUTHUs = new EntitySet<CAUTHU>(new Action<CAUTHU>(this.attach_CAUTHUs), new Action<CAUTHU>(this.detach_CAUTHUs));
			this._HUANLUYENVIENs = new EntitySet<HUANLUYENVIEN>(new Action<HUANLUYENVIEN>(this.attach_HUANLUYENVIENs), new Action<HUANLUYENVIEN>(this.detach_HUANLUYENVIENs));
			this._TRANDAUs = new EntitySet<TRANDAU>(new Action<TRANDAU>(this.attach_TRANDAUs), new Action<TRANDAU>(this.detach_TRANDAUs));
			this._TRANDAUs1 = new EntitySet<TRANDAU>(new Action<TRANDAU>(this.attach_TRANDAUs1), new Action<TRANDAU>(this.detach_TRANDAUs1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADB", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADB
		{
			get
			{
				return this._MADB;
			}
			set
			{
				if ((this._MADB != value))
				{
					this.OnMADBChanging(value);
					this.SendPropertyChanging();
					this._MADB = value;
					this.SendPropertyChanged("MADB");
					this.OnMADBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDOIBONG", DbType="NVarChar(30)")]
		public string TENDOIBONG
		{
			get
			{
				return this._TENDOIBONG;
			}
			set
			{
				if ((this._TENDOIBONG != value))
				{
					this.OnTENDOIBONGChanging(value);
					this.SendPropertyChanging();
					this._TENDOIBONG = value;
					this.SendPropertyChanged("TENDOIBONG");
					this.OnTENDOIBONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONGCAUTHU", DbType="TinyInt")]
		public System.Nullable<byte> SOLUONGCAUTHU
		{
			get
			{
				return this._SOLUONGCAUTHU;
			}
			set
			{
				if ((this._SOLUONGCAUTHU != value))
				{
					this.OnSOLUONGCAUTHUChanging(value);
					this.SendPropertyChanging();
					this._SOLUONGCAUTHU = value;
					this.SendPropertyChanged("SOLUONGCAUTHU");
					this.OnSOLUONGCAUTHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENSANNHA", DbType="NVarChar(30)")]
		public string TENSANNHA
		{
			get
			{
				return this._TENSANNHA;
			}
			set
			{
				if ((this._TENSANNHA != value))
				{
					this.OnTENSANNHAChanging(value);
					this.SendPropertyChanging();
					this._TENSANNHA = value;
					this.SendPropertyChanged("TENSANNHA");
					this.OnTENSANNHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTHANH", DbType="NVarChar(30)")]
		public string TINHTHANH
		{
			get
			{
				return this._TINHTHANH;
			}
			set
			{
				if ((this._TINHTHANH != value))
				{
					this.OnTINHTHANHChanging(value);
					this.SendPropertyChanging();
					this._TINHTHANH = value;
					this.SendPropertyChanged("TINHTHANH");
					this.OnTINHTHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYTHANHLAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYTHANHLAP
		{
			get
			{
				return this._NGAYTHANHLAP;
			}
			set
			{
				if ((this._NGAYTHANHLAP != value))
				{
					this.OnNGAYTHANHLAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYTHANHLAP = value;
					this.SendPropertyChanged("NGAYTHANHLAP");
					this.OnNGAYTHANHLAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOBANTHANG", DbType="SmallInt")]
		public System.Nullable<short> SOBANTHANG
		{
			get
			{
				return this._SOBANTHANG;
			}
			set
			{
				if ((this._SOBANTHANG != value))
				{
					this.OnSOBANTHANGChanging(value);
					this.SendPropertyChanging();
					this._SOBANTHANG = value;
					this.SendPropertyChanged("SOBANTHANG");
					this.OnSOBANTHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOBANTHUA", DbType="SmallInt")]
		public System.Nullable<short> SOBANTHUA
		{
			get
			{
				return this._SOBANTHUA;
			}
			set
			{
				if ((this._SOBANTHUA != value))
				{
					this.OnSOBANTHUAChanging(value);
					this.SendPropertyChanging();
					this._SOBANTHUA = value;
					this.SendPropertyChanged("SOBANTHUA");
					this.OnSOBANTHUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGDIEM", DbType="SmallInt")]
		public System.Nullable<short> TONGDIEM
		{
			get
			{
				return this._TONGDIEM;
			}
			set
			{
				if ((this._TONGDIEM != value))
				{
					this.OnTONGDIEMChanging(value);
					this.SendPropertyChanging();
					this._TONGDIEM = value;
					this.SendPropertyChanged("TONGDIEM");
					this.OnTONGDIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOIBONG_BANTHANG", Storage="_BANTHANGs", ThisKey="MADB", OtherKey="MADB")]
		public EntitySet<BANTHANG> BANTHANGs
		{
			get
			{
				return this._BANTHANGs;
			}
			set
			{
				this._BANTHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOIBONG_CAUTHU", Storage="_CAUTHUs", ThisKey="MADB", OtherKey="MADB")]
		public EntitySet<CAUTHU> CAUTHUs
		{
			get
			{
				return this._CAUTHUs;
			}
			set
			{
				this._CAUTHUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOIBONG_HUANLUYENVIEN", Storage="_HUANLUYENVIENs", ThisKey="MADB", OtherKey="MADB")]
		public EntitySet<HUANLUYENVIEN> HUANLUYENVIENs
		{
			get
			{
				return this._HUANLUYENVIENs;
			}
			set
			{
				this._HUANLUYENVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOIBONG_TRANDAU", Storage="_TRANDAUs", ThisKey="MADB", OtherKey="DOI1")]
		public EntitySet<TRANDAU> TRANDAUs
		{
			get
			{
				return this._TRANDAUs;
			}
			set
			{
				this._TRANDAUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOIBONG_TRANDAU1", Storage="_TRANDAUs1", ThisKey="MADB", OtherKey="DOI2")]
		public EntitySet<TRANDAU> TRANDAUs1
		{
			get
			{
				return this._TRANDAUs1;
			}
			set
			{
				this._TRANDAUs1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BANTHANGs(BANTHANG entity)
		{
			this.SendPropertyChanging();
			entity.DOIBONG = this;
		}
		
		private void detach_BANTHANGs(BANTHANG entity)
		{
			this.SendPropertyChanging();
			entity.DOIBONG = null;
		}
		
		private void attach_CAUTHUs(CAUTHU entity)
		{
			this.SendPropertyChanging();
			entity.DOIBONG = this;
		}
		
		private void detach_CAUTHUs(CAUTHU entity)
		{
			this.SendPropertyChanging();
			entity.DOIBONG = null;
		}
		
		private void attach_HUANLUYENVIENs(HUANLUYENVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DOIBONG = this;
		}
		
		private void detach_HUANLUYENVIENs(HUANLUYENVIEN entity)
		{
			this.SendPropertyChanging();
			entity.DOIBONG = null;
		}
		
		private void attach_TRANDAUs(TRANDAU entity)
		{
			this.SendPropertyChanging();
			entity.DOIBONG = this;
		}
		
		private void detach_TRANDAUs(TRANDAU entity)
		{
			this.SendPropertyChanging();
			entity.DOIBONG = null;
		}
		
		private void attach_TRANDAUs1(TRANDAU entity)
		{
			this.SendPropertyChanging();
			entity.DOIBONG1 = this;
		}
		
		private void detach_TRANDAUs1(TRANDAU entity)
		{
			this.SendPropertyChanging();
			entity.DOIBONG1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRONGTAI")]
	public partial class TRONGTAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATT;
		
		private string _HOTEN;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _DIACHI;
		
		private string _QUOCTICH;
		
		private System.Nullable<byte> _SONAMKINHNGHIEM;
		
		private string _AVATAR;
		
		private System.Nullable<bool> _LOAITRONGTAI;
		
		private EntitySet<TRANDAU_TRONGTAI> _TRANDAU_TRONGTAIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATTChanging(string value);
    partial void OnMATTChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnQUOCTICHChanging(string value);
    partial void OnQUOCTICHChanged();
    partial void OnSONAMKINHNGHIEMChanging(System.Nullable<byte> value);
    partial void OnSONAMKINHNGHIEMChanged();
    partial void OnAVATARChanging(string value);
    partial void OnAVATARChanged();
    partial void OnLOAITRONGTAIChanging(System.Nullable<bool> value);
    partial void OnLOAITRONGTAIChanged();
    #endregion
		
		public TRONGTAI()
		{
			this._TRANDAU_TRONGTAIs = new EntitySet<TRANDAU_TRONGTAI>(new Action<TRANDAU_TRONGTAI>(this.attach_TRANDAU_TRONGTAIs), new Action<TRANDAU_TRONGTAI>(this.detach_TRANDAU_TRONGTAIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATT", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATT
		{
			get
			{
				return this._MATT;
			}
			set
			{
				if ((this._MATT != value))
				{
					this.OnMATTChanging(value);
					this.SendPropertyChanging();
					this._MATT = value;
					this.SendPropertyChanged("MATT");
					this.OnMATTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(30)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUOCTICH", DbType="NVarChar(20)")]
		public string QUOCTICH
		{
			get
			{
				return this._QUOCTICH;
			}
			set
			{
				if ((this._QUOCTICH != value))
				{
					this.OnQUOCTICHChanging(value);
					this.SendPropertyChanging();
					this._QUOCTICH = value;
					this.SendPropertyChanged("QUOCTICH");
					this.OnQUOCTICHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONAMKINHNGHIEM", DbType="TinyInt")]
		public System.Nullable<byte> SONAMKINHNGHIEM
		{
			get
			{
				return this._SONAMKINHNGHIEM;
			}
			set
			{
				if ((this._SONAMKINHNGHIEM != value))
				{
					this.OnSONAMKINHNGHIEMChanging(value);
					this.SendPropertyChanging();
					this._SONAMKINHNGHIEM = value;
					this.SendPropertyChanged("SONAMKINHNGHIEM");
					this.OnSONAMKINHNGHIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVATAR", DbType="NVarChar(500)")]
		public string AVATAR
		{
			get
			{
				return this._AVATAR;
			}
			set
			{
				if ((this._AVATAR != value))
				{
					this.OnAVATARChanging(value);
					this.SendPropertyChanging();
					this._AVATAR = value;
					this.SendPropertyChanged("AVATAR");
					this.OnAVATARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAITRONGTAI", DbType="Bit")]
		public System.Nullable<bool> LOAITRONGTAI
		{
			get
			{
				return this._LOAITRONGTAI;
			}
			set
			{
				if ((this._LOAITRONGTAI != value))
				{
					this.OnLOAITRONGTAIChanging(value);
					this.SendPropertyChanging();
					this._LOAITRONGTAI = value;
					this.SendPropertyChanged("LOAITRONGTAI");
					this.OnLOAITRONGTAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRONGTAI_TRANDAU_TRONGTAI", Storage="_TRANDAU_TRONGTAIs", ThisKey="MATT", OtherKey="MATT")]
		public EntitySet<TRANDAU_TRONGTAI> TRANDAU_TRONGTAIs
		{
			get
			{
				return this._TRANDAU_TRONGTAIs;
			}
			set
			{
				this._TRANDAU_TRONGTAIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TRANDAU_TRONGTAIs(TRANDAU_TRONGTAI entity)
		{
			this.SendPropertyChanging();
			entity.TRONGTAI = this;
		}
		
		private void detach_TRANDAU_TRONGTAIs(TRANDAU_TRONGTAI entity)
		{
			this.SendPropertyChanging();
			entity.TRONGTAI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUYDINH")]
	public partial class QUYDINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAQD;
		
		private System.Nullable<int> _PLAYER_AGE_MAX;
		
		private System.Nullable<int> _PLAYER_AGE_MIN;
		
		private System.Nullable<int> _PLAYER_NUM_MAX;
		
		private System.Nullable<int> _PLAYER_NUM_MIN;
		
		private System.Nullable<int> _PLAYER_FOREIGN_MAX;
		
		private System.Nullable<int> _THOI_DIEM_GHI_BAN_MAX;
		
		private System.Nullable<int> _SCORE_THANG;
		
		private System.Nullable<int> _SCORE_THUA;
		
		private System.Nullable<int> _SCORE_HOA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAQDChanging(int value);
    partial void OnMAQDChanged();
    partial void OnPLAYER_AGE_MAXChanging(System.Nullable<int> value);
    partial void OnPLAYER_AGE_MAXChanged();
    partial void OnPLAYER_AGE_MINChanging(System.Nullable<int> value);
    partial void OnPLAYER_AGE_MINChanged();
    partial void OnPLAYER_NUM_MAXChanging(System.Nullable<int> value);
    partial void OnPLAYER_NUM_MAXChanged();
    partial void OnPLAYER_NUM_MINChanging(System.Nullable<int> value);
    partial void OnPLAYER_NUM_MINChanged();
    partial void OnPLAYER_FOREIGN_MAXChanging(System.Nullable<int> value);
    partial void OnPLAYER_FOREIGN_MAXChanged();
    partial void OnTHOI_DIEM_GHI_BAN_MAXChanging(System.Nullable<int> value);
    partial void OnTHOI_DIEM_GHI_BAN_MAXChanged();
    partial void OnSCORE_THANGChanging(System.Nullable<int> value);
    partial void OnSCORE_THANGChanged();
    partial void OnSCORE_THUAChanging(System.Nullable<int> value);
    partial void OnSCORE_THUAChanged();
    partial void OnSCORE_HOAChanging(System.Nullable<int> value);
    partial void OnSCORE_HOAChanged();
    #endregion
		
		public QUYDINH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAQD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAQD
		{
			get
			{
				return this._MAQD;
			}
			set
			{
				if ((this._MAQD != value))
				{
					this.OnMAQDChanging(value);
					this.SendPropertyChanging();
					this._MAQD = value;
					this.SendPropertyChanged("MAQD");
					this.OnMAQDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAYER_AGE_MAX", DbType="Int")]
		public System.Nullable<int> PLAYER_AGE_MAX
		{
			get
			{
				return this._PLAYER_AGE_MAX;
			}
			set
			{
				if ((this._PLAYER_AGE_MAX != value))
				{
					this.OnPLAYER_AGE_MAXChanging(value);
					this.SendPropertyChanging();
					this._PLAYER_AGE_MAX = value;
					this.SendPropertyChanged("PLAYER_AGE_MAX");
					this.OnPLAYER_AGE_MAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAYER_AGE_MIN", DbType="Int")]
		public System.Nullable<int> PLAYER_AGE_MIN
		{
			get
			{
				return this._PLAYER_AGE_MIN;
			}
			set
			{
				if ((this._PLAYER_AGE_MIN != value))
				{
					this.OnPLAYER_AGE_MINChanging(value);
					this.SendPropertyChanging();
					this._PLAYER_AGE_MIN = value;
					this.SendPropertyChanged("PLAYER_AGE_MIN");
					this.OnPLAYER_AGE_MINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAYER_NUM_MAX", DbType="Int")]
		public System.Nullable<int> PLAYER_NUM_MAX
		{
			get
			{
				return this._PLAYER_NUM_MAX;
			}
			set
			{
				if ((this._PLAYER_NUM_MAX != value))
				{
					this.OnPLAYER_NUM_MAXChanging(value);
					this.SendPropertyChanging();
					this._PLAYER_NUM_MAX = value;
					this.SendPropertyChanged("PLAYER_NUM_MAX");
					this.OnPLAYER_NUM_MAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAYER_NUM_MIN", DbType="Int")]
		public System.Nullable<int> PLAYER_NUM_MIN
		{
			get
			{
				return this._PLAYER_NUM_MIN;
			}
			set
			{
				if ((this._PLAYER_NUM_MIN != value))
				{
					this.OnPLAYER_NUM_MINChanging(value);
					this.SendPropertyChanging();
					this._PLAYER_NUM_MIN = value;
					this.SendPropertyChanged("PLAYER_NUM_MIN");
					this.OnPLAYER_NUM_MINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAYER_FOREIGN_MAX", DbType="Int")]
		public System.Nullable<int> PLAYER_FOREIGN_MAX
		{
			get
			{
				return this._PLAYER_FOREIGN_MAX;
			}
			set
			{
				if ((this._PLAYER_FOREIGN_MAX != value))
				{
					this.OnPLAYER_FOREIGN_MAXChanging(value);
					this.SendPropertyChanging();
					this._PLAYER_FOREIGN_MAX = value;
					this.SendPropertyChanged("PLAYER_FOREIGN_MAX");
					this.OnPLAYER_FOREIGN_MAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOI_DIEM_GHI_BAN_MAX", DbType="Int")]
		public System.Nullable<int> THOI_DIEM_GHI_BAN_MAX
		{
			get
			{
				return this._THOI_DIEM_GHI_BAN_MAX;
			}
			set
			{
				if ((this._THOI_DIEM_GHI_BAN_MAX != value))
				{
					this.OnTHOI_DIEM_GHI_BAN_MAXChanging(value);
					this.SendPropertyChanging();
					this._THOI_DIEM_GHI_BAN_MAX = value;
					this.SendPropertyChanged("THOI_DIEM_GHI_BAN_MAX");
					this.OnTHOI_DIEM_GHI_BAN_MAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCORE_THANG", DbType="Int")]
		public System.Nullable<int> SCORE_THANG
		{
			get
			{
				return this._SCORE_THANG;
			}
			set
			{
				if ((this._SCORE_THANG != value))
				{
					this.OnSCORE_THANGChanging(value);
					this.SendPropertyChanging();
					this._SCORE_THANG = value;
					this.SendPropertyChanged("SCORE_THANG");
					this.OnSCORE_THANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCORE_THUA", DbType="Int")]
		public System.Nullable<int> SCORE_THUA
		{
			get
			{
				return this._SCORE_THUA;
			}
			set
			{
				if ((this._SCORE_THUA != value))
				{
					this.OnSCORE_THUAChanging(value);
					this.SendPropertyChanging();
					this._SCORE_THUA = value;
					this.SendPropertyChanged("SCORE_THUA");
					this.OnSCORE_THUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCORE_HOA", DbType="Int")]
		public System.Nullable<int> SCORE_HOA
		{
			get
			{
				return this._SCORE_HOA;
			}
			set
			{
				if ((this._SCORE_HOA != value))
				{
					this.OnSCORE_HOAChanging(value);
					this.SendPropertyChanging();
					this._SCORE_HOA = value;
					this.SendPropertyChanged("SCORE_HOA");
					this.OnSCORE_HOAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HUANLUYENVIEN")]
	public partial class HUANLUYENVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHLV;
		
		private string _MADB;
		
		private string _HOTEN;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _DIACHI;
		
		private string _QUOCTICH;
		
		private System.Nullable<byte> _SONAMKINHNGHIEM;
		
		private string _AVATAR;
		
		private System.Nullable<bool> _LOAIHLV;
		
		private EntityRef<DOIBONG> _DOIBONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHLVChanging(string value);
    partial void OnMAHLVChanged();
    partial void OnMADBChanging(string value);
    partial void OnMADBChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnQUOCTICHChanging(string value);
    partial void OnQUOCTICHChanged();
    partial void OnSONAMKINHNGHIEMChanging(System.Nullable<byte> value);
    partial void OnSONAMKINHNGHIEMChanged();
    partial void OnAVATARChanging(string value);
    partial void OnAVATARChanged();
    partial void OnLOAIHLVChanging(System.Nullable<bool> value);
    partial void OnLOAIHLVChanged();
    #endregion
		
		public HUANLUYENVIEN()
		{
			this._DOIBONG = default(EntityRef<DOIBONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHLV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHLV
		{
			get
			{
				return this._MAHLV;
			}
			set
			{
				if ((this._MAHLV != value))
				{
					this.OnMAHLVChanging(value);
					this.SendPropertyChanging();
					this._MAHLV = value;
					this.SendPropertyChanged("MAHLV");
					this.OnMAHLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADB", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADB
		{
			get
			{
				return this._MADB;
			}
			set
			{
				if ((this._MADB != value))
				{
					if (this._DOIBONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADBChanging(value);
					this.SendPropertyChanging();
					this._MADB = value;
					this.SendPropertyChanged("MADB");
					this.OnMADBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(30)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUOCTICH", DbType="NVarChar(20)")]
		public string QUOCTICH
		{
			get
			{
				return this._QUOCTICH;
			}
			set
			{
				if ((this._QUOCTICH != value))
				{
					this.OnQUOCTICHChanging(value);
					this.SendPropertyChanging();
					this._QUOCTICH = value;
					this.SendPropertyChanged("QUOCTICH");
					this.OnQUOCTICHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONAMKINHNGHIEM", DbType="TinyInt")]
		public System.Nullable<byte> SONAMKINHNGHIEM
		{
			get
			{
				return this._SONAMKINHNGHIEM;
			}
			set
			{
				if ((this._SONAMKINHNGHIEM != value))
				{
					this.OnSONAMKINHNGHIEMChanging(value);
					this.SendPropertyChanging();
					this._SONAMKINHNGHIEM = value;
					this.SendPropertyChanged("SONAMKINHNGHIEM");
					this.OnSONAMKINHNGHIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVATAR", DbType="NVarChar(500)")]
		public string AVATAR
		{
			get
			{
				return this._AVATAR;
			}
			set
			{
				if ((this._AVATAR != value))
				{
					this.OnAVATARChanging(value);
					this.SendPropertyChanging();
					this._AVATAR = value;
					this.SendPropertyChanged("AVATAR");
					this.OnAVATARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAIHLV", DbType="Bit")]
		public System.Nullable<bool> LOAIHLV
		{
			get
			{
				return this._LOAIHLV;
			}
			set
			{
				if ((this._LOAIHLV != value))
				{
					this.OnLOAIHLVChanging(value);
					this.SendPropertyChanging();
					this._LOAIHLV = value;
					this.SendPropertyChanged("LOAIHLV");
					this.OnLOAIHLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOIBONG_HUANLUYENVIEN", Storage="_DOIBONG", ThisKey="MADB", OtherKey="MADB", IsForeignKey=true)]
		public DOIBONG DOIBONG
		{
			get
			{
				return this._DOIBONG.Entity;
			}
			set
			{
				DOIBONG previousValue = this._DOIBONG.Entity;
				if (((previousValue != value) 
							|| (this._DOIBONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOIBONG.Entity = null;
						previousValue.HUANLUYENVIENs.Remove(this);
					}
					this._DOIBONG.Entity = value;
					if ((value != null))
					{
						value.HUANLUYENVIENs.Add(this);
						this._MADB = value.MADB;
					}
					else
					{
						this._MADB = default(string);
					}
					this.SendPropertyChanged("DOIBONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRANDAU_TRONGTAI")]
	public partial class TRANDAU_TRONGTAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATD;
		
		private string _MATT;
		
		private EntityRef<TRONGTAI> _TRONGTAI;
		
		private EntityRef<TRANDAU> _TRANDAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATDChanging(string value);
    partial void OnMATDChanged();
    partial void OnMATTChanging(string value);
    partial void OnMATTChanged();
    #endregion
		
		public TRANDAU_TRONGTAI()
		{
			this._TRONGTAI = default(EntityRef<TRONGTAI>);
			this._TRANDAU = default(EntityRef<TRANDAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATD", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATD
		{
			get
			{
				return this._MATD;
			}
			set
			{
				if ((this._MATD != value))
				{
					if (this._TRANDAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATDChanging(value);
					this.SendPropertyChanging();
					this._MATD = value;
					this.SendPropertyChanged("MATD");
					this.OnMATDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATT", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATT
		{
			get
			{
				return this._MATT;
			}
			set
			{
				if ((this._MATT != value))
				{
					if (this._TRONGTAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATTChanging(value);
					this.SendPropertyChanging();
					this._MATT = value;
					this.SendPropertyChanged("MATT");
					this.OnMATTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRONGTAI_TRANDAU_TRONGTAI", Storage="_TRONGTAI", ThisKey="MATT", OtherKey="MATT", IsForeignKey=true)]
		public TRONGTAI TRONGTAI
		{
			get
			{
				return this._TRONGTAI.Entity;
			}
			set
			{
				TRONGTAI previousValue = this._TRONGTAI.Entity;
				if (((previousValue != value) 
							|| (this._TRONGTAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRONGTAI.Entity = null;
						previousValue.TRANDAU_TRONGTAIs.Remove(this);
					}
					this._TRONGTAI.Entity = value;
					if ((value != null))
					{
						value.TRANDAU_TRONGTAIs.Add(this);
						this._MATT = value.MATT;
					}
					else
					{
						this._MATT = default(string);
					}
					this.SendPropertyChanged("TRONGTAI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRANDAU_TRANDAU_TRONGTAI", Storage="_TRANDAU", ThisKey="MATD", OtherKey="MATD", IsForeignKey=true)]
		public TRANDAU TRANDAU
		{
			get
			{
				return this._TRANDAU.Entity;
			}
			set
			{
				TRANDAU previousValue = this._TRANDAU.Entity;
				if (((previousValue != value) 
							|| (this._TRANDAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRANDAU.Entity = null;
						previousValue.TRANDAU_TRONGTAIs.Remove(this);
					}
					this._TRANDAU.Entity = value;
					if ((value != null))
					{
						value.TRANDAU_TRONGTAIs.Add(this);
						this._MATD = value.MATD;
					}
					else
					{
						this._MATD = default(string);
					}
					this.SendPropertyChanged("TRANDAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRANDAU")]
	public partial class TRANDAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATD;
		
		private System.Nullable<System.DateTime> _NGAYDIENRA;
		
		private string _DOI1;
		
		private string _DOI2;
		
		private System.Nullable<short> _SCORED1;
		
		private System.Nullable<short> _SCORED2;
		
		private string _TENSAN;
		
		private System.Nullable<byte> _VONGDAU;
		
		private System.Nullable<bool> _GHINHAN;
		
		private EntitySet<BANTHANG> _BANTHANGs;
		
		private EntitySet<TRANDAU_TRONGTAI> _TRANDAU_TRONGTAIs;
		
		private EntityRef<DOIBONG> _DOIBONG;
		
		private EntityRef<DOIBONG> _DOIBONG1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATDChanging(string value);
    partial void OnMATDChanged();
    partial void OnNGAYDIENRAChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYDIENRAChanged();
    partial void OnDOI1Changing(string value);
    partial void OnDOI1Changed();
    partial void OnDOI2Changing(string value);
    partial void OnDOI2Changed();
    partial void OnSCORED1Changing(System.Nullable<short> value);
    partial void OnSCORED1Changed();
    partial void OnSCORED2Changing(System.Nullable<short> value);
    partial void OnSCORED2Changed();
    partial void OnTENSANChanging(string value);
    partial void OnTENSANChanged();
    partial void OnVONGDAUChanging(System.Nullable<byte> value);
    partial void OnVONGDAUChanged();
    partial void OnGHINHANChanging(System.Nullable<bool> value);
    partial void OnGHINHANChanged();
    #endregion
		
		public TRANDAU()
		{
			this._BANTHANGs = new EntitySet<BANTHANG>(new Action<BANTHANG>(this.attach_BANTHANGs), new Action<BANTHANG>(this.detach_BANTHANGs));
			this._TRANDAU_TRONGTAIs = new EntitySet<TRANDAU_TRONGTAI>(new Action<TRANDAU_TRONGTAI>(this.attach_TRANDAU_TRONGTAIs), new Action<TRANDAU_TRONGTAI>(this.detach_TRANDAU_TRONGTAIs));
			this._DOIBONG = default(EntityRef<DOIBONG>);
			this._DOIBONG1 = default(EntityRef<DOIBONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATD", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATD
		{
			get
			{
				return this._MATD;
			}
			set
			{
				if ((this._MATD != value))
				{
					this.OnMATDChanging(value);
					this.SendPropertyChanging();
					this._MATD = value;
					this.SendPropertyChanged("MATD");
					this.OnMATDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYDIENRA", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYDIENRA
		{
			get
			{
				return this._NGAYDIENRA;
			}
			set
			{
				if ((this._NGAYDIENRA != value))
				{
					this.OnNGAYDIENRAChanging(value);
					this.SendPropertyChanging();
					this._NGAYDIENRA = value;
					this.SendPropertyChanged("NGAYDIENRA");
					this.OnNGAYDIENRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOI1", DbType="NChar(10)")]
		public string DOI1
		{
			get
			{
				return this._DOI1;
			}
			set
			{
				if ((this._DOI1 != value))
				{
					if (this._DOIBONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDOI1Changing(value);
					this.SendPropertyChanging();
					this._DOI1 = value;
					this.SendPropertyChanged("DOI1");
					this.OnDOI1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOI2", DbType="NChar(10)")]
		public string DOI2
		{
			get
			{
				return this._DOI2;
			}
			set
			{
				if ((this._DOI2 != value))
				{
					if (this._DOIBONG1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDOI2Changing(value);
					this.SendPropertyChanging();
					this._DOI2 = value;
					this.SendPropertyChanged("DOI2");
					this.OnDOI2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCORED1", DbType="SmallInt")]
		public System.Nullable<short> SCORED1
		{
			get
			{
				return this._SCORED1;
			}
			set
			{
				if ((this._SCORED1 != value))
				{
					this.OnSCORED1Changing(value);
					this.SendPropertyChanging();
					this._SCORED1 = value;
					this.SendPropertyChanged("SCORED1");
					this.OnSCORED1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCORED2", DbType="SmallInt")]
		public System.Nullable<short> SCORED2
		{
			get
			{
				return this._SCORED2;
			}
			set
			{
				if ((this._SCORED2 != value))
				{
					this.OnSCORED2Changing(value);
					this.SendPropertyChanging();
					this._SCORED2 = value;
					this.SendPropertyChanged("SCORED2");
					this.OnSCORED2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENSAN", DbType="NVarChar(30)")]
		public string TENSAN
		{
			get
			{
				return this._TENSAN;
			}
			set
			{
				if ((this._TENSAN != value))
				{
					this.OnTENSANChanging(value);
					this.SendPropertyChanging();
					this._TENSAN = value;
					this.SendPropertyChanged("TENSAN");
					this.OnTENSANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VONGDAU", DbType="TinyInt")]
		public System.Nullable<byte> VONGDAU
		{
			get
			{
				return this._VONGDAU;
			}
			set
			{
				if ((this._VONGDAU != value))
				{
					this.OnVONGDAUChanging(value);
					this.SendPropertyChanging();
					this._VONGDAU = value;
					this.SendPropertyChanged("VONGDAU");
					this.OnVONGDAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHINHAN", DbType="Bit")]
		public System.Nullable<bool> GHINHAN
		{
			get
			{
				return this._GHINHAN;
			}
			set
			{
				if ((this._GHINHAN != value))
				{
					this.OnGHINHANChanging(value);
					this.SendPropertyChanging();
					this._GHINHAN = value;
					this.SendPropertyChanged("GHINHAN");
					this.OnGHINHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRANDAU_BANTHANG", Storage="_BANTHANGs", ThisKey="MATD", OtherKey="MATD")]
		public EntitySet<BANTHANG> BANTHANGs
		{
			get
			{
				return this._BANTHANGs;
			}
			set
			{
				this._BANTHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRANDAU_TRANDAU_TRONGTAI", Storage="_TRANDAU_TRONGTAIs", ThisKey="MATD", OtherKey="MATD")]
		public EntitySet<TRANDAU_TRONGTAI> TRANDAU_TRONGTAIs
		{
			get
			{
				return this._TRANDAU_TRONGTAIs;
			}
			set
			{
				this._TRANDAU_TRONGTAIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOIBONG_TRANDAU", Storage="_DOIBONG", ThisKey="DOI1", OtherKey="MADB", IsForeignKey=true)]
		public DOIBONG DOIBONG
		{
			get
			{
				return this._DOIBONG.Entity;
			}
			set
			{
				DOIBONG previousValue = this._DOIBONG.Entity;
				if (((previousValue != value) 
							|| (this._DOIBONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOIBONG.Entity = null;
						previousValue.TRANDAUs.Remove(this);
					}
					this._DOIBONG.Entity = value;
					if ((value != null))
					{
						value.TRANDAUs.Add(this);
						this._DOI1 = value.MADB;
					}
					else
					{
						this._DOI1 = default(string);
					}
					this.SendPropertyChanged("DOIBONG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOIBONG_TRANDAU1", Storage="_DOIBONG1", ThisKey="DOI2", OtherKey="MADB", IsForeignKey=true)]
		public DOIBONG DOIBONG1
		{
			get
			{
				return this._DOIBONG1.Entity;
			}
			set
			{
				DOIBONG previousValue = this._DOIBONG1.Entity;
				if (((previousValue != value) 
							|| (this._DOIBONG1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOIBONG1.Entity = null;
						previousValue.TRANDAUs1.Remove(this);
					}
					this._DOIBONG1.Entity = value;
					if ((value != null))
					{
						value.TRANDAUs1.Add(this);
						this._DOI2 = value.MADB;
					}
					else
					{
						this._DOI2 = default(string);
					}
					this.SendPropertyChanged("DOIBONG1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BANTHANGs(BANTHANG entity)
		{
			this.SendPropertyChanging();
			entity.TRANDAU = this;
		}
		
		private void detach_BANTHANGs(BANTHANG entity)
		{
			this.SendPropertyChanging();
			entity.TRANDAU = null;
		}
		
		private void attach_TRANDAU_TRONGTAIs(TRANDAU_TRONGTAI entity)
		{
			this.SendPropertyChanging();
			entity.TRANDAU = this;
		}
		
		private void detach_TRANDAU_TRONGTAIs(TRANDAU_TRONGTAI entity)
		{
			this.SendPropertyChanging();
			entity.TRANDAU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIBANTHANG")]
	public partial class LOAIBANTHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private char _MABT;
		
		private string _TENBT;
		
		private EntitySet<BANTHANG> _BANTHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMABTChanging(char value);
    partial void OnMABTChanged();
    partial void OnTENBTChanging(string value);
    partial void OnTENBTChanged();
    #endregion
		
		public LOAIBANTHANG()
		{
			this._BANTHANGs = new EntitySet<BANTHANG>(new Action<BANTHANG>(this.attach_BANTHANGs), new Action<BANTHANG>(this.detach_BANTHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MABT", DbType="NChar(1) NOT NULL", IsPrimaryKey=true)]
		public char MABT
		{
			get
			{
				return this._MABT;
			}
			set
			{
				if ((this._MABT != value))
				{
					this.OnMABTChanging(value);
					this.SendPropertyChanging();
					this._MABT = value;
					this.SendPropertyChanged("MABT");
					this.OnMABTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENBT", DbType="NChar(30)")]
		public string TENBT
		{
			get
			{
				return this._TENBT;
			}
			set
			{
				if ((this._TENBT != value))
				{
					this.OnTENBTChanging(value);
					this.SendPropertyChanging();
					this._TENBT = value;
					this.SendPropertyChanged("TENBT");
					this.OnTENBTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIBANTHANG_BANTHANG", Storage="_BANTHANGs", ThisKey="MABT", OtherKey="LOAIBT")]
		public EntitySet<BANTHANG> BANTHANGs
		{
			get
			{
				return this._BANTHANGs;
			}
			set
			{
				this._BANTHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BANTHANGs(BANTHANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAIBANTHANG = this;
		}
		
		private void detach_BANTHANGs(BANTHANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAIBANTHANG = null;
		}
	}
}
#pragma warning restore 1591
